name: Ping Keep Alive URLs

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    env:
      URLS: ${{ secrets.KEEP_ALIVE_URLS }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    steps:
      - name: Hacer ping a las URLs y enviar alerta si falla alguna
        run: |
          echo "Iniciando pings..."

          IFS=',' read -ra URL_ARRAY <<< "$URLS"
          error_urls=""

          for url in "${URL_ARRAY[@]}"; do
            echo "Haciendo ping a: $url"
            status_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")

            if [ "$status_code" -ne 200 ]; then
              echo "⚠️ Error al hacer ping a $url (Status: $status_code)"
              error_urls+="• $url (status: $status_code)\n"
            fi
          done

          if [ -n "$error_urls" ]; then
            echo "Enviando alerta a Discord..."
            payload="{\"content\": \"❌ *Alerta de Ping:* Las siguientes URL fallaron:\n$error_urls\"}"
            curl -X POST -H "Content-Type: application/json" -d "$payload" "$DISCORD_WEBHOOK_URL"
          else
            echo "✅ Todos los pings se realizaron con éxito."
          fi
