name: Keep Alive Ping

on:
  schedule:
    - cron: '*/10 * * * *'  # Cada 10 minutos
  workflow_dispatch:         # Permite lanzarlo manualmente desde GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping + Alerta
        run: |
          echo "Ejecutando pings a las URLs:"
          error_urls=""
          while IFS= read -r url; do
            if [[ -z "$url" || "$url" =~ ^# ]]; then
              continue
            fi
            echo "→ $url"
            code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            echo "  ↳ Código HTTP: $code"
            if [[ "$code" -ge 400 ]]; then
              error_urls+="$url → Código $code\n"
            fi
          done < .urls
      
          if [[ -n "$error_urls" ]]; then
            payload=$(jq -n --arg content ":warning: **Error en keep-alive**\n\n$error_urls" '{content: $content}')
            curl -X POST -H "Content-Type: application/json" \
              -d "$payload" \
              "${{ secrets.DISCORD_WEBHOOK }}"
          else
            echo "✅ Todas las URLs respondieron correctamente."
          fi
