name: Keep Alive Ping

on:
  schedule:
    - cron: '*/10 * * * *'  # Cada 10 minutos
  workflow_dispatch:         # Permite lanzarlo manualmente desde GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a apps
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://url-shortener-backend-5rxc.onrender.com/urls
          curl -s -o /dev/null -w "%{http_code}" https://lafavoritabar.site/la_favorita_logo.png
          curl -s -o /dev/null -w "%{http_code}" https://planet-gamer-backend.onrender.com/games
