name: Keep Alive Ping

on:
  schedule:
    - cron: '*/10 * * * *'  # Cada 10 minutos
  workflow_dispatch:        # Permite ejecutarlo manualmente desde GitHub

jobs:
  ping_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Leer URLs y enviar alerta si fallan
        run: |
          echo "Ejecutando pings a las URLs:"
          error_urls=""

          while IFS= read -r url; do
            # Ignora líneas vacías o que comienzan por #
            if [[ -z "$url" || "$url" =~ ^# ]]; then
              continue
            fi

            echo "→ $url"
            code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            echo "  ↳ Código HTTP: $code"

            if [[ "$code" -ge 400 ]]; then
              error_urls+="$url → Código $code\\n"
            fi
          done < .urls.txt

          if [[ -n "$error_urls" ]]; then
            echo "❌ Fallos detectados:"
            echo -e "$error_urls"

            payload="{\"content\":\":warning: **Error en keep-alive**\\n\\n$error_urls\"}"
            curl -X POST -H "Content-Type: application/json" \
              -d "$payload" \
              "${{ secrets.DISCORD_WEBHOOK }}"
          else
            echo "✅ Todas las URLs respondieron correctamente."
          fi
